# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180209_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Produced automatically from the slug', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('name', 'email')]),
        ),
    ]
